### ISSUE TITLE
Could you do a tag please

### ISSUE THREAD

**Issue by harikt** [ryakad/pandoc-php#10]
Hi @ryakad , 

I was just looking at packagist and found your repo. You have done a good work on it.

What about tagging a release ? So people don't need to point to `dev-master` . 

If you are interested more on the same see slide number 165 : https://beau.io/talks/2014/11/11/managing-dependencies-with-composer-phpworld-2014/

Thank you

**Comment by ryakad** [comment]
Thanks for the suggestion @harikt  I have started semantic versioning and pushed up a v1.0.0.

**Comment by harikt** [comment]
:+1:  Thank you.
