### ISSUE TITLE
Script can't find PanDoc

### ISSUE THREAD

**Issue by learncss** [ryakad/pandoc-php#16]
I know this isn't an issue, but I'm lost on this issue. I'm getting this error and I don't know how to make it work. I'm using MAMP.

Fatal error: Uncaught exception 'Pandoc\PandocException' with message 'Unable to locate pandoc' in /Applications/MAMP/htdocs/publishing/pandoc-php-master/src/Pandoc/Pandoc.php:133 Stack trace: #0 /Applications/MAMP/htdocs/publishing/pandoc-php-master/test.php(6): Pandoc\Pandoc->__construct() #1 {main} thrown in /Applications/MAMP/htdocs/publishing/pandoc-php-master/src/Pandoc/Pandoc.php on line 133

Any idea how I can make this work?

**Comment by ryakad** [comment]
It is unable to find the pandoc binary.

Pandoc is likely either not installed or not in your path.  You also pass an argument to the contructor to set the path to the pandoc binary.

```php
$pandoc = new Pandoc('/path/to/pandoc');
```

**Comment by LucaCappelletti94** [comment]
Hello, I am facing the very same issue but [pandoc](https://pandoc.org/) is very much installed (if I run `pandoc --help` I get the standard output). How may I proceed?

Thank you!
Luca
