### ISSUE TITLE
Convert to pdf

### ISSUE THREAD

**Issue by n1c01a5** [ryakad/pandoc-php#3]
I try convert my content to pdf with 

```
$pandoc = new Pandoc();
$options = array(
    "from"  => "plain",
    "to"    => "pdf"
);
$result = $pandoc->runWith($content, $options);
```

But I have this error:
`ContextErrorException: Warning: file_get_contents(/tmp/pandoc53523a3db40e2.pdf): failed to open stream`

Thanks for your help.

**Comment by vishalmelmatti** [comment]
did it work? I am also trying to convert markdown to pdf using this lib ?

**Comment by n1c01a5** [comment]
Yes, it's works. Do you have any problems?

**Comment by vishalmelmatti** [comment]
Sorry, got it working using runWith.
